services:
  ora-12c:
    image: quay.io/maksymbilenko/oracle-12c:latest
    environment:
      DBCA_TOTAL_MEMORY: 1024
      WEB_CONSOLE: false 
    ports:
      - "1521:1521"
    volumes:
      - ./db:/u01/app/oracle