services:
  ora-12c:
    image: quay.io/maksymbilenko/oracle-12c:latest
    environment:
      DBCA_TOTAL_MEMORY: 2048
      WEB_CONSOLE: false 
    ports:
      - "1521:1521"
    volumes:
      - ora-db:/u01/app/oracle
volumes:
  ora-db:
