CREATE SEQUENCE PARTY_SEQ   START WITH 1   INCREMENT BY 1  NOCACHE   NOCYCLE;
CREATE TABLE PARTY(
    ID NUMBER(19) PRIMARY KEY NOT NULL,
    VERSION NUMBER(19) NOT NULL,
    CREATED_AT DATE NOT NULL,
    CREATED_BY VARCHAR2(100) NOT NULL,
    MODIFIED_AT DATE,
    MODIFIED_BY VARCHAR2(100),

    TYPE_FLAG VARCHAR2(100) NOT NULL,
    KEY29 NUMBER(19) NOT NULL

);

CREATE SEQUENCE CUSTOMER_SEQ   START WITH 1   INCREMENT BY 1  NOCACHE   NOCYCLE;
CREATE TABLE CUSTOMER(
    ID NUMBER(19) PRIMARY KEY NOT NULL,
    VERSION NUMBER(19) NOT NULL,
    CREATED_AT DATE NOT NULL,
    CREATED_BY VARCHAR2(100) NOT NULL,
    MODIFIED_AT DATE,
    MODIFIED_BY VARCHAR2(100),

    CIF VARCHAR2(100) NOT NULL,
    FULL_NAME VARCHAR2(100) NOT NULL

);

CREATE SEQUENCE BANK_SEQ   START WITH 1   INCREMENT BY 1  NOCACHE   NOCYCLE;
CREATE TABLE BANK(
    ID NUMBER(19) PRIMARY KEY NOT NULL,
    VERSION NUMBER(19) NOT NULL,
    CREATED_AT DATE NOT NULL,
    CREATED_BY VARCHAR2(100) NOT NULL,
    MODIFIED_AT DATE,
    MODIFIED_BY VARCHAR2(100),

    TITLE VARCHAR2(100) NOT NULL

);

CREATE SEQUENCE ISSUE_MASTER_SEQ   START WITH 1   INCREMENT BY 1  NOCACHE   NOCYCLE;
CREATE TABLE ISSUE_MASTER(
    ID NUMBER(19) PRIMARY KEY NOT NULL,
    VERSION NUMBER(19) NOT NULL,
    CREATED_AT DATE NOT NULL,
    CREATED_BY VARCHAR2(100) NOT NULL,
    MODIFIED_AT DATE,
    MODIFIED_BY VARCHAR2(100),

    REFERENCE VARCHAR2(100),
    INPUT_BRANCH VARCHAR2(20),
    BEHALF_BRANCH VARCHAR2(20),
    ISSUE_DATE DATE,
    EXPIRY_DATE DATE,
    AMOUNT NUMBER(19,4),
    CCY CHAR(3),
    APPLICANT_FK  NUMBER(19),
    BENEFICIARY_FK NUMBER(19),

    CONSTRAINT FK_ISSUE_MASTER_PARTY_APPLICANT FOREIGN KEY (APPLICANT_FK) REFERENCES PARTY(ID),
    CONSTRAINT FK_ISSUE_MASTER_PARTY_BENEFICIARY FOREIGN KEY (BENEFICIARY_FK) REFERENCES PARTY(ID)

);

CREATE SEQUENCE ISSUE_EVENT_SEQ   START WITH 1   INCREMENT BY 1  NOCACHE   NOCYCLE;
CREATE TABLE ISSUE_EVENT(
    ID NUMBER(19) PRIMARY KEY NOT NULL,
    VERSION NUMBER(19) NOT NULL,
    CREATED_AT DATE NOT NULL,
    CREATED_BY VARCHAR2(100) NOT NULL,
    MODIFIED_AT DATE,
    MODIFIED_BY VARCHAR2(100),

    MASTER_FK NUMBER(19) NOT NULL,
    APPLICANT_REFERENCE VARCHAR2(100),
    ISSUE_DATE DATE,
    EXPIRY_DATE DATE,
    AMOUNT NUMBER(19,4),
    CCY CHAR(3),
    APPLICANT_FK  NUMBER(19),
    BENEFICIARY_FK NUMBER(19),

    CONSTRAINT FK_ISSUE_EVENT_ISSUE_MASTER FOREIGN KEY (MASTER_FK) REFERENCES ISSUE_MASTER(ID),
    CONSTRAINT FK_ISSUE_EVENT_PARTY_APPLICANT FOREIGN KEY (APPLICANT_FK) REFERENCES PARTY(ID),
    CONSTRAINT FK_ISSUE_EVENT_PARTY_BENEFICIARY FOREIGN KEY (BENEFICIARY_FK) REFERENCES PARTY(ID)

);

