
BEGIN
  EXECUTE IMMEDIATE 'DROP SEQUENCE ISSUE_EVENT_SEQ';
EXCEPTION
  WHEN OTHERS THEN
     IF SQLCODE != -942 THEN
        RAISE;
     END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE ISSUE_EVENT';
EXCEPTION
  WHEN OTHERS THEN
     IF SQLCODE != -942 THEN
        RAISE;
     END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'DROP SEQUENCE ISSUE_MASTER_SEQ';
EXCEPTION
  WHEN OTHERS THEN
     IF SQLCODE != -942 THEN
        RAISE;
     END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE ISSUE_MASTER';
EXCEPTION
  WHEN OTHERS THEN
     IF SQLCODE != -942 THEN
        RAISE;
     END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'DROP  SEQUENCE PARTY_SEQ';
EXCEPTION
  WHEN OTHERS THEN
     IF SQLCODE != -942 THEN
        RAISE;
     END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE PARTY';
EXCEPTION
  WHEN OTHERS THEN
     IF SQLCODE != -942 THEN
        RAISE;
     END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'DROP SEQUENCE CUSTOMER_SEQ';
EXCEPTION
  WHEN OTHERS THEN
     IF SQLCODE != -942 THEN
        RAISE;
     END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE CUSTOMER';
EXCEPTION
  WHEN OTHERS THEN
     IF SQLCODE != -942 THEN
        RAISE;
     END IF;
END;
/


BEGIN
  EXECUTE IMMEDIATE 'DROP SEQUENCE BANK_SEQ';
EXCEPTION
  WHEN OTHERS THEN
     IF SQLCODE != -942 THEN
        RAISE;
     END IF;
END;
/


BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE BANK';
EXCEPTION
  WHEN OTHERS THEN
     IF SQLCODE != -942 THEN
        RAISE;
     END IF;
END;
/
