DROP SEQUENCE IF EXISTS JV_COMMIT_PK_SEQ;
DROP SEQUENCE IF EXISTS JV_GLOBAL_ID_PK_SEQ;
DROP SEQUENCE IF EXISTS JV_SNAPSHOT_PK_SEQ;

DROP TABLE IF EXISTS FX_JV_COMMIT_PROPERTY;
DROP TABLE IF EXISTS FX_JV_SNAPSHOT;
DROP TABLE IF EXISTS FX_JV_COMMIT;
DROP TABLE IF EXISTS FX_JV_GLOBAL_ID;